return {
  "onsails/lspkind.nvim",
  config = function()
    require('lspkind').init({
      mode = 'symbol_text',
      maxwidth = 50,
      symbol_map = {
        Text = "󰊄",
        Method = "m",
        Function = "󰊕",
        Constructor = "",
        Field = "",
        Variable = "󰫧",
        Class = "",
        Interface = "",
        Module = "",
        Property = "",
        Unit = "",
        Value = "",
        Enum = "",
        Keyword = "󰌆",
        Snippet = "",
        Color = "",
        File = "",
        Reference = "",
        Folder = "",
        EnumMember = "",
        Constant = "",
        Struct = "",
        Event = "",
        Operator = "",
        TypeParameter = "󰉺",
      },
    })
  end,
}
